### PR TITLE
Fix encoding error for gist_tag

### LINKED ISSUE #18: The noscript tag generates encoding error within Liquid
When I insert one of my gists with Unicode characters in it (e.g. [this one](https://gist.githubusercontent.com/gergelypolonkai/498a32297f39b4960ad7/raw/555c8802a5d694c572643ceb7998c0a7b28e3c1b/helper.py)) I get a Liquid error:

    Liquid Exception: incompatible character encodings: UTF-8 and ASCII-8BIT

After a bit of debugging it turned out that the contents of the Gist is not encoded right, most probably because github itself doesn’t send a Content-Type header or any other means of specifying the encoding of the raw Gist.

### PR DESCRIPTION
**Pull request by akerl**
This should fix #18 and #22 by ensuring gists are loaded into the same encoding as the site itself

### CODE REVIEW

File: lib/jekyll-gist/gist_tag.rb [hunk 1]
```diff
@@ -69,7 +70,7 @@ def fetch_raw_code(gist_id, filename = nil)
             read_timeout: 3, open_timeout: 3) do |http|
             request = Net::HTTP::Get.new uri.to_s
             response = http.request(request)
-            response.body
+            response.body.force_encoding(@encoding)
```
Comment (parkr) [inline lib/jekyll-gist/gist_tag.rb]: I think GitHub always sends back UTF-8. Maybe @benbalter can help with this?

Comment (akerl) [inline lib/jekyll-gist/gist_tag.rb]: Perhaps, but if the Jekyll user sets their site to use something else, and jekyll-gist returns utf-8, is Liquid not going to error out as it is now, with the mix of utf-8 and ascii 8bit?

**Comment by parkr** [comment]
Released in v1.3.5! Thanks :) https://github.com/jekyll/jekyll-gist/releases/tag/v1.3.5
